Задание 2022_10_03
Lancoid/skypro_education_endwork pull request #3
Opened 2022-11-10 15:35 UTC by Lancoid

2022-11-10 18:05 UTC, OlgaLugacheva requested changes

2022-11-10 18:05 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/controller/AuthController.java
> +        try {
не вижу причины тут менять логику и ловить Throwable

2022-11-10 18:05 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/dto/AdsCreateDto.java
> +    private MultipartFile image;
dto по схеме содержит именно String а не MultipartFile

2022-11-10 18:05 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/service/auth/AuthServiceImpl.java
> +        } catch (Throwable throwable) {
зачем?

2022-11-10 18:05 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/repository/AdsImageRepository.java
> +    AdsImage findByFileNameEqualsIgnoreCase(@NonNull String fileName);
стоит сделать Optional

2022-11-10 20:37 UTC, Lancoid commented on src/main/java/ru/skypro/homework/repository/AdsImageRepository.java
> +    AdsImage findByFileNameEqualsIgnoreCase(@NonNull String fileName);
исправлено

2022-11-10 20:40 UTC, Lancoid commented on src/main/java/ru/skypro/homework/controller/AuthController.java
> +        try {
исправил

2022-11-10 20:42 UTC, Lancoid commented on src/main/java/ru/skypro/homework/service/auth/AuthServiceImpl.java
> +        } catch (Throwable throwable) {
исправил

2022-11-10 20:47 UTC, Lancoid commented on src/main/java/ru/skypro/homework/dto/AdsCreateDto.java
> +    private MultipartFile image;
исправил

2022-11-11 12:26 UTC, OlgaLugacheva requested changes

2022-11-11 12:26 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/config/WebSecurityConfig.java
раз нет изменений в 4-ой части, оставлю комментарий тут: 
cors нужно раздизэблить и я не вижу фильтров ни здесь ни над контроллерами
не все запросы могут выполнить анонимные пользователи - смотрим требования

2022-11-11 14:09 UTC, Lancoid commented on src/main/java/ru/skypro/homework/config/WebSecurityConfig.java
исправил

2022-11-12 10:50 UTC, OlgaLugacheva requested changes

2022-11-12 10:50 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +@PreAuthorize("hasAnyAuthority('USER', 'ADMIN')")
вот на весь контроллер , конечно , не надо

смотрим требования - получить объявления могут и неавторизованные пользователи.

2022-11-12 11:21 UTC, Lancoid commented on src/main/java/ru/skypro/homework/controller/AdsController.java
> +@PreAuthorize("hasAnyAuthority('USER', 'ADMIN')")
исправил

2022-11-12 11:22 UTC, merged